openapi: 3.0.0
info:
  title: NAMyServiceAPIApigee
  version: 1.0.0
servers:
  - url: https://httpbin.org
paths:
  /ip:
    get:
      operationId: getIpAddress
      summary: Get IP Address
      responses:
        '200':
          description: OK
