openapi: 3.0.0
info:
  title: MyServiceAPIkong
  version: 1.0.0
servers:
  - url: https://httpbin.org
paths:
  /ip:
    get:
      operationId: getIpAddress
      summary: Get IP Address
      responses:
        '200':
          description: OK
          headers:
            X-RateLimit-Limit:
              description: The maximum number of requests that the consumer is permitted to make in a given time window.
              schema:
                type: integer
                format: int32
                minimum: 0
                maximum: 1000
            X-RateLimit-Remaining:
              description: The number of requests remaining in the current time window.
              schema:
                type: integer
                format: int32
                minimum: 0
                maximum: 1000
            X-RateLimit-Reset:
              description: The time at which the current rate limit window resets.
              schema:
                type: integer
                format: int32
                minimum: 0
                maximum: 2147483647  # Adjust the maximum value as needed
        '400':
          description: Bad Request
          headers:
            X-RateLimit-Limit:
              description: The maximum number of requests that the consumer is permitted to make in a given time window.
              schema:
                type: integer
                format: int32
                minimum: 0
                maximum: 1000
            X-RateLimit-Remaining:
              description: The number of requests remaining in the current time window.
              schema:
                type: integer
                format: int32
                minimum: 0
                maximum: 1000
            X-RateLimit-Reset:
              description: The time at which the current rate limit window resets.
              schema:
                type: integer
                format: int32
                minimum: 0
                maximum: 2147483647  # Adjust the maximum value as needed
        '401':
          description: Unauthorized
          headers:
            X-RateLimit-Limit:
              description: The maximum number of requests that the consumer is permitted to make in a given time window.
              schema:
                type: integer
                format: int32
                minimum: 0
                maximum: 1000
            X-RateLimit-Remaining:
              description: The number of requests remaining in the current time window.
              schema:
                type: integer
                format: int32
                minimum: 0
                maximum: 1000
            X-RateLimit-Reset:
              description: The time at which the current rate limit window resets.
              schema:
                type: integer
                format: int32
                minimum: 0
                maximum: 2147483647  # Adjust the maximum value as needed
